workflows:
  node-multi-build:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ['12', '14']
              prom-client-version: ['10', '11', '12', '13', '14']
            # exclude:
            #   - node-version: '6'
            #     prom-client-version: '12'
orbs:
  node: circleci/node@16
version: 2.1
jobs:
  test:
    parameters:
      node-version:
        type: string
      prom-client-version:
        type: string
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-npm: true
          install-yarn: false
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install
          cache-path: ~/node_modules
          include-branch-in-cache-key: false
      - run:
          name: Install prom-client@<< parameters.prom-client-version >>
          command: npm i prom-client@^<< parameters.prom-client-version >> --ignore-engines
      - run:
          name: Test prom-client@<< parameters.prom-client-version >>
          command: npm test
